### ISSUE TITLE
Can't get CDC service to start

### ISSUE THREAD

**Issue by khashish** [eventuate-tram/eventuate-tram-sagas-examples-customers-and-orders#16]
When running ./gradlew mysqlComposeUp

I get the following messages and the CDC fails to start

Waiting for cdcservice_1 to become healthy (it's starting)
Waiting for cdcservice_1 to become healthy (it's starting)
Waiting for cdcservice_1 to become healthy (it's unhealthy)

**Comment by GitProdEnv** [comment]
Just try it again, and make sure if you are on Ubuntu, to use the pc's ip address. (console: ifconfig)

Then execute
export DOCKER_HOST_IP: %yourPcIpAddressHERE

For more details, see here http://eventuate.io/docs/usingdocker.html

**Comment by khashish** [comment]
Thanks that worked perfectly.

**Comment by mostafa358** [comment]
i try to run mysqlComposeUp but i get this error

Waiting for cdcservice_1 to become healthy (it's starting)
Waiting for cdcservice_1 to become healthy (it's starting)
Waiting for cdcservice_1 to become healthy (it's unhealthy)

and after 15minutes project building stoped with error.|
I did your recommendation  
"export DOCKER_HOST_IP: %yourPcIpAddressHERE"
and nothing happened.
please tell us how to resolve that.
