### ISSUE TITLE
Can't get CDC service to start (Waiting for cdcservice_1 to become healthy (it's unhealthy))

### ISSUE THREAD

**Issue by mostafa358** [eventuate-tram/eventuate-tram-sagas-examples-customers-and-orders#40]
i try to run mysqlComposeUp but i get this error

Waiting for cdcservice_1 to become healthy (it's starting)
Waiting for cdcservice_1 to become healthy (it's starting)
Waiting for cdcservice_1 to become healthy (it's unhealthy)

and after 15minutes project building stoped with error.|
I did your recommendation
"export DOCKER_HOST_IP: %yourPcIpAddressHERE"
and nothing happened.
please tell us how to resolve that.

**Comment by RohithSurya** [comment]
@mostafa358 Did you try stopping and again running mysqlComposeUp?
I have once faced this issue, but got resolved after stopping and running again.
